package com.vasylyna.fooddelivery.order;
import com.vasylyna.fooddelivery.cart.*;import com.vasylyna.fooddelivery.common.ResourceNotFoundException;import com.vasylyna.fooddelivery.user.*;
import jakarta.validation.constraints.*;import java.math.BigDecimal;import java.util.*;
import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;
@Service public class OrderService{
 private final CartRepository carts;private final CartItemRepository cartItems;private final CustomerOrderRepository orders;private final OrderItemRepository orderItems;private final AddressRepository addresses;private final AppUserRepository users;
 public OrderService(CartRepository carts,CartItemRepository cartItems,CustomerOrderRepository orders,OrderItemRepository orderItems,AddressRepository addresses,AppUserRepository users){this.carts=carts;this.cartItems=cartItems;this.orders=orders;this.orderItems=orderItems;this.addresses=addresses;this.users=users;}
 @Transactional public OrderView checkout(String email,CheckoutRequest req){AppUser user=users.findByEmailIgnoreCase(email).orElseThrow();Cart cart=carts.findByEmail(email).orElseThrow(()->new IllegalArgumentException("Your cart is empty"));var lines=cartItems.findByCart_Id(cart.getId());if(lines.isEmpty())throw new IllegalArgumentException("Your cart is empty");if(lines.stream().anyMatch(i->!i.getMenuItem().isAvailable()))throw new IllegalArgumentException("One or more items in your cart are no longer available");BigDecimal subtotal=lines.stream().map(i->i.getMenuItem().getPrice().multiply(BigDecimal.valueOf(i.getQuantity()))).reduce(BigDecimal.ZERO,BigDecimal::add);BigDecimal fee=CartService.deliveryFeeFor(lines);Address address=addresses.save(new Address(user,req.label(),req.street(),req.city(),req.postalCode(),req.instructions()));CustomerOrder order=orders.save(new CustomerOrder(user,address,subtotal,fee,subtotal.add(fee)));for(var line:lines)orderItems.save(new OrderItem(order,line.getMenuItem(),line.getMenuItem().getName(),line.getMenuItem().getPrice(),line.getQuantity()));cartItems.deleteByCart_Id(cart.getId());return view(order);}
 @Transactional(readOnly=true) public List<OrderView> history(String email){return orders.findByUser_EmailOrderByCreatedAtDesc(email).stream().map(this::view).toList();}
 @Transactional(readOnly=true) public OrderView get(String email,Long id){return view(orders.findByIdAndUser_Email(id,email).orElseThrow(()->new ResourceNotFoundException("Order was not found")));}
 @Transactional(readOnly=true) public List<OrderView> all(){return orders.findAll().stream().map(this::view).toList();}
 @Transactional public OrderView status(Long id,OrderStatus status){CustomerOrder o=orders.findById(id).orElseThrow(()->new ResourceNotFoundException("Order was not found"));boolean allowed=switch(o.getStatus()){case PENDING->status==OrderStatus.CONFIRMED||status==OrderStatus.CANCELLED;case CONFIRMED->status==OrderStatus.PREPARING||status==OrderStatus.CANCELLED;case PREPARING->status==OrderStatus.OUT_FOR_DELIVERY||status==OrderStatus.CANCELLED;case OUT_FOR_DELIVERY->status==OrderStatus.DELIVERED;case DELIVERED,CANCELLED->false;};if(!allowed)throw new IllegalArgumentException("Order cannot move from "+o.getStatus()+" to "+status);o.setStatus(status);return view(o);}
 private OrderView view(CustomerOrder o){var lines=orderItems.findByOrder_Id(o.getId()).stream().map(i->new OrderLine(i.getItemName(),i.getUnitPrice(),i.getQuantity())).toList();return new OrderView(o.getId(),o.getStatus().name(),o.getSubtotal(),o.getDeliveryFee(),o.getTotal(),o.getCreatedAt(),o.getAddress().getStreet(),o.getAddress().getCity(),o.getAddress().getPostalCode(),lines);}
 public record CheckoutRequest(@NotBlank @Size(max=180) String street,@NotBlank @Size(max=100) String city,@NotBlank @Size(max=20) String postalCode,@Size(max=80) String label,@Size(max=500) String instructions){}
 public record OrderLine(String itemName,BigDecimal unitPrice,int quantity){}public record OrderView(Long id,String status,BigDecimal subtotal,BigDecimal deliveryFee,BigDecimal total,java.time.Instant createdAt,String street,String city,String postalCode,List<OrderLine> items){}
}
